# Generated by Django 5.2.15 on 2026-07-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_dashboard_is_deleted_dashboardline_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title English')),
                ('title_bn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title Bangla')),
                ('div_id', models.CharField(blank=True, max_length=55, null=True, unique=True)),
                ('div_class', models.CharField(blank=True, max_length=255, null=True)),
                ('widget_type', models.CharField(choices=[('url', 'URL'), ('template', 'Template'), ('html', 'HTML')], default='url', max_length=20)),
                ('system_url', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.CharField(blank=True, help_text='dashboard/widgets/project_summary.html', max_length=255, null=True)),
                ('html_code', models.TextField(blank=True, help_text='Use only for controlled custom widgets.', null=True, verbose_name='HTML Code')),
                ('additional_configuration', models.JSONField(blank=True, default=dict, help_text='Store extra widget settings in JSON format.', verbose_name='Additional Configuration')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistical_dashboards', to='core.siteconfig')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
            },
        ),
    ]
